// Code generated by internal/cmd/generate. DO NOT EDIT.

package openhandle

import "time"

type Comment = CommentCore

type CommentCore struct {
	Author              PostAuthor     `json:"author"`
	ID                  string         `json:"id"`
	IsLikedByPostAuthor *bool          `json:"is_liked_by_post_author"`
	IsPinned            *bool          `json:"is_pinned"`
	Media               []PostMedia    `json:"media"`
	Metrics             CommentMetrics `json:"metrics"`
	ParentID            *string        `json:"parent_id"`
	PinnedPosition      *int64         `json:"pinned_position"`
	PublishedAt         time.Time      `json:"published_at"`
	ReplyPreview        []Comment      `json:"reply_preview,omitempty"`
	Text                string         `json:"text"`
	ThreadRootID        *string        `json:"thread_root_id"`
}

type CommentMetrics struct {
	Bookmarks *int64 `json:"bookmarks"`
	Likes     *int64 `json:"likes"`
	Quotes    *int64 `json:"quotes"`
	Replies   *int64 `json:"replies"`
	Reposts   *int64 `json:"reposts"`
	Views     *int64 `json:"views"`
}

type Entity = EntityCore

type EntityCore struct {
	Attributes  map[string]any  `json:"attributes"`
	Description *string         `json:"description"`
	Handle      *string         `json:"handle"`
	ID          string          `json:"id"`
	Image       *MediaReference `json:"image"`
	Kind        string          `json:"kind"`
	Metrics     map[string]any  `json:"metrics"`
	Name        *string         `json:"name"`
	URL         *string         `json:"url"`
}

type EntityReference struct {
	Handle *string         `json:"handle,omitempty"`
	ID     string          `json:"id"`
	Image  *MediaReference `json:"image,omitempty"`
	Name   *string         `json:"name,omitempty"`
	URL    *string         `json:"url,omitempty"`
}

type ErrorEnvelope struct {
	Error struct {
		Code      string         `json:"code"`
		Details   map[string]any `json:"details,omitempty"`
		Message   string         `json:"message"`
		RequestID string         `json:"request_id"`
		Retryable bool           `json:"retryable"`
	} `json:"error"`
}

type Hashtag struct {
	Description *string         `json:"description"`
	ID          string          `json:"id"`
	Image       *MediaReference `json:"image"`
	Metrics     struct {
		Posts *int64 `json:"posts"`
		Views *int64 `json:"views"`
	} `json:"metrics"`
	Name string `json:"name"`
}

type InstagramClipMetadata struct {
	Author      *EntityReference `json:"author,omitempty"`
	Caption     *string          `json:"caption,omitempty"`
	Duration    *float64         `json:"duration,omitempty"`
	Height      *int64           `json:"height,omitempty"`
	ID          string           `json:"id"`
	Media       []PostMedia      `json:"media"`
	Music       *PostMusic       `json:"music,omitempty"`
	PlayCount   *int64           `json:"play_count,omitempty"`
	PublishedAt *time.Time       `json:"published_at,omitempty"`
	Title       *string          `json:"title,omitempty"`
	ViewCount   *int64           `json:"view_count,omitempty"`
	Width       *int64           `json:"width,omitempty"`
}

type InstagramComment struct {
	CommentCore
}

type InstagramCommentMetadata struct {
	CanComment       *bool  `json:"can_comment,omitempty"`
	CanViewMore      *bool  `json:"can_view_more,omitempty"`
	CommentCount     *int64 `json:"comment_count,omitempty"`
	CommentsDisabled *bool  `json:"comments_disabled,omitempty"`
	ID               string `json:"id"`
	PreviewCount     *int64 `json:"preview_count,omitempty"`
}

type InstagramCommentModeration struct {
	ID          string   `json:"id"`
	IsBullying  *bool    `json:"is_bullying,omitempty"`
	IsOffensive *bool    `json:"is_offensive,omitempty"`
	IsSpam      *bool    `json:"is_spam,omitempty"`
	Reasons     []string `json:"reasons"`
	Score       *float64 `json:"score,omitempty"`
	Text        *string  `json:"text,omitempty"`
}

type InstagramEntity struct {
	EntityCore
}

type InstagramHighlight struct {
	Cover     *MediaReference  `json:"cover,omitempty"`
	ID        string           `json:"id"`
	ItemCount *int64           `json:"item_count,omitempty"`
	Items     []InstagramStory `json:"items"`
	Owner     *EntityReference `json:"owner,omitempty"`
	Title     *string          `json:"title,omitempty"`
}

type InstagramLocationGuide struct {
	Author      *EntityReference `json:"author,omitempty"`
	Description *string          `json:"description,omitempty"`
	ID          string           `json:"id"`
	Image       *MediaReference  `json:"image,omitempty"`
	ItemCount   *int64           `json:"item_count,omitempty"`
	Location    *PostLocation    `json:"location,omitempty"`
	Title       *string          `json:"title,omitempty"`
	URL         *string          `json:"url,omitempty"`
}

type InstagramMusicStream struct {
	Bitrate   *int64     `json:"bitrate,omitempty"`
	Duration  *float64   `json:"duration,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	ID        string     `json:"id"`
	MimeType  *string    `json:"mime_type,omitempty"`
	Page      *int64     `json:"page,omitempty"`
	URL       *string    `json:"url,omitempty"`
}

type InstagramOEmbed struct {
	AuthorName   *string         `json:"author_name,omitempty"`
	AuthorURL    *string         `json:"author_url,omitempty"`
	Height       *int64          `json:"height,omitempty"`
	Html         *string         `json:"html,omitempty"`
	ID           string          `json:"id"`
	ProviderName *string         `json:"provider_name,omitempty"`
	ProviderURL  *string         `json:"provider_url,omitempty"`
	Thumbnail    *MediaReference `json:"thumbnail,omitempty"`
	Title        *string         `json:"title,omitempty"`
	Type         *string         `json:"type,omitempty"`
	URL          *string         `json:"url,omitempty"`
	Width        *int64          `json:"width,omitempty"`
}

type InstagramPlayCountBreakdown struct {
	Facebook  *int64 `json:"facebook"`
	Instagram *int64 `json:"instagram"`
}

type InstagramPost struct {
	PostCore
	Collaborators     []PostAuthor           `json:"collaborators"`
	Extended          *InstagramPostExtended `json:"extended,omitempty"`
	IsAd              *bool                  `json:"is_ad"`
	IsPaidPartnership *bool                  `json:"is_paid_partnership"`
	Location          *PostLocation          `json:"location"`
	Metrics           InstagramPostMetrics   `json:"metrics"`
	Music             *PostMusic             `json:"music"`
	Shortcode         *string                `json:"shortcode"`
	Sponsors          []PostAuthor           `json:"sponsors"`
	TaggedUsers       []PostAuthor           `json:"tagged_users"`
}

type InstagramPostExtended struct {
	AccessibilityCaption *string `json:"accessibility_caption"`
	LikeCountsHidden     *bool   `json:"like_counts_hidden"`
	ProductType          *string `json:"product_type"`
}

type InstagramPostInsight struct {
	AverageWatchTime *float64 `json:"average_watch_time,omitempty"`
	Comments         *int64   `json:"comments,omitempty"`
	Follows          *int64   `json:"follows,omitempty"`
	ID               string   `json:"id"`
	Impressions      *int64   `json:"impressions,omitempty"`
	Interactions     *int64   `json:"interactions,omitempty"`
	Likes            *int64   `json:"likes,omitempty"`
	Plays            *int64   `json:"plays,omitempty"`
	ProfileVisits    *int64   `json:"profile_visits,omitempty"`
	Reach            *int64   `json:"reach,omitempty"`
	Saves            *int64   `json:"saves,omitempty"`
	Shares           *int64   `json:"shares,omitempty"`
	Views            *int64   `json:"views,omitempty"`
	WatchTime        *float64 `json:"watch_time,omitempty"`
}

type InstagramPostMetrics struct {
	PostMetrics
	PlayCountBreakdown *InstagramPlayCountBreakdown `json:"play_count_breakdown,omitempty"`
}

type InstagramProfile struct {
	ProfileCore
	Extended *InstagramProfileExtended `json:"extended,omitempty"`
}

type InstagramProfileAbout struct {
	Bio                 *string    `json:"bio,omitempty"`
	Category            *string    `json:"category,omitempty"`
	Country             *string    `json:"country,omitempty"`
	DisplayName         *string    `json:"display_name,omitempty"`
	ExternalURL         *string    `json:"external_url,omitempty"`
	FormerUsernameCount *int64     `json:"former_username_count,omitempty"`
	Handle              *string    `json:"handle,omitempty"`
	ID                  string     `json:"id"`
	IsBusiness          *bool      `json:"is_business,omitempty"`
	IsPrivate           *bool      `json:"is_private,omitempty"`
	IsVerified          *bool      `json:"is_verified,omitempty"`
	JoinedAt            *time.Time `json:"joined_at,omitempty"`
}

type InstagramProfileExtended struct {
	AccountTypeCode        *int64        `json:"account_type_code"`
	AddressStreet          *string       `json:"address_street"`
	BioLinks               []ProfileLink `json:"bio_links"`
	BusinessContactMethod  *string       `json:"business_contact_method"`
	City                   *string       `json:"city"`
	Latitude               *float64      `json:"latitude"`
	Longitude              *float64      `json:"longitude"`
	PostalCode             *string       `json:"postal_code"`
	PublicEmail            *string       `json:"public_email"`
	PublicPhoneCountryCode *string       `json:"public_phone_country_code"`
	PublicPhoneNumber      *string       `json:"public_phone_number"`
}

type InstagramProfileSummary struct {
	Avatar      *MediaReference `json:"avatar,omitempty"`
	Bio         *string         `json:"bio,omitempty"`
	Category    *string         `json:"category,omitempty"`
	DisplayName *string         `json:"display_name,omitempty"`
	Followers   *int64          `json:"followers,omitempty"`
	Handle      *string         `json:"handle,omitempty"`
	ID          string          `json:"id"`
	IsPrivate   *bool           `json:"is_private,omitempty"`
	IsVerified  *bool           `json:"is_verified,omitempty"`
	URL         *string         `json:"url,omitempty"`
}

type InstagramSearchResult struct {
	Author      *EntityReference     `json:"author,omitempty"`
	Description *string              `json:"description,omitempty"`
	Handle      *string              `json:"handle,omitempty"`
	ID          string               `json:"id"`
	Image       *MediaReference      `json:"image,omitempty"`
	Metrics     *SearchResultMetrics `json:"metrics,omitempty"`
	Title       *string              `json:"title,omitempty"`
	Type        *string              `json:"type,omitempty"`
	URL         *string              `json:"url,omitempty"`
}

type InstagramStory struct {
	Author        *EntityReference  `json:"author,omitempty"`
	CanQuickReply *bool             `json:"can_quick_reply,omitempty"`
	CanReply      *bool             `json:"can_reply,omitempty"`
	CanReshare    *bool             `json:"can_reshare,omitempty"`
	ExpiresAt     *time.Time        `json:"expires_at,omitempty"`
	Hashtags      []string          `json:"hashtags"`
	ID            string            `json:"id"`
	Links         []StoryLink       `json:"links"`
	Locations     []PostLocation    `json:"locations"`
	Media         []PostMedia       `json:"media"`
	Mentions      []EntityReference `json:"mentions"`
	PublishedAt   *time.Time        `json:"published_at,omitempty"`
	Shortcode     *string           `json:"shortcode,omitempty"`
	Stickers      []StorySticker    `json:"stickers"`
	Type          *string           `json:"type,omitempty"`
}

type InstagramTemplate struct {
	Author      *EntityReference `json:"author,omitempty"`
	Description *string          `json:"description,omitempty"`
	Duration    *float64         `json:"duration,omitempty"`
	ID          string           `json:"id"`
	Media       []PostMedia      `json:"media"`
	Name        *string          `json:"name,omitempty"`
	Type        *string          `json:"type,omitempty"`
	URL         *string          `json:"url,omitempty"`
}

type Location struct {
	Address     *string  `json:"address"`
	Category    *string  `json:"category"`
	City        *string  `json:"city"`
	CountryCode *string  `json:"country_code"`
	ID          string   `json:"id"`
	Latitude    *float64 `json:"latitude"`
	Longitude   *float64 `json:"longitude"`
	Name        string   `json:"name"`
	Phone       *string  `json:"phone"`
	PostalCode  *string  `json:"postal_code"`
	Region      *string  `json:"region"`
	Website     *string  `json:"website"`
}

type MediaReference struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	URL       string     `json:"url"`
}

type MessageEnvelope struct {
	Message string `json:"message"`
}

type Money struct {
	Amount   string  `json:"amount"`
	Currency *string `json:"currency,omitempty"`
}

type Music struct {
	Album        *string          `json:"album"`
	Artist       *PostMusicArtist `json:"artist"`
	Artwork      *MediaReference  `json:"artwork"`
	Audio        *MediaReference  `json:"audio"`
	Duration     *float64         `json:"duration"`
	ID           string           `json:"id"`
	IsCommercial *bool            `json:"is_commercial"`
	IsExplicit   *bool            `json:"is_explicit"`
	IsOriginal   *bool            `json:"is_original"`
	Metrics      struct {
		Posts *int64 `json:"posts"`
	} `json:"metrics"`
	Title string `json:"title"`
}

type PostAuthor struct {
	Avatar      *MediaReference `json:"avatar"`
	DisplayName *string         `json:"display_name"`
	Handle      string          `json:"handle"`
	ID          string          `json:"id"`
	IsVerified  *bool           `json:"is_verified"`
}

type PostCore struct {
	Author           PostAuthor  `json:"author"`
	Caption          *string     `json:"caption"`
	CommentsDisabled *bool       `json:"comments_disabled"`
	Format           string      `json:"format"`
	Hashtags         []string    `json:"hashtags"`
	ID               string      `json:"id"`
	Media            []PostMedia `json:"media"`
	Mentions         []string    `json:"mentions"`
	PublishedAt      time.Time   `json:"published_at"`
	Title            *string     `json:"title"`
	Type             string      `json:"type"`
	URL              string      `json:"url"`
}

type PostLocation struct {
	Address     *string  `json:"address"`
	Category    *string  `json:"category"`
	City        *string  `json:"city"`
	CountryCode *string  `json:"country_code"`
	ID          *string  `json:"id"`
	Latitude    *float64 `json:"latitude"`
	Longitude   *float64 `json:"longitude"`
	Name        *string  `json:"name"`
	Phone       *string  `json:"phone"`
	PostalCode  *string  `json:"postal_code"`
	Region      *string  `json:"region"`
	Website     *string  `json:"website"`
}

type PostMedia struct {
	AltText   *string            `json:"alt_text,omitempty"`
	Duration  *float64           `json:"duration,omitempty"`
	ExpiresAt *time.Time         `json:"expires_at,omitempty"`
	Height    *int64             `json:"height,omitempty"`
	ID        *string            `json:"id,omitempty"`
	Thumbnail *MediaReference    `json:"thumbnail,omitempty"`
	Type      string             `json:"type"`
	URL       string             `json:"url"`
	Variants  []PostMediaVariant `json:"variants,omitempty"`
	Width     *int64             `json:"width,omitempty"`
}

type PostMediaVariant struct {
	Bitrate     *int64     `json:"bitrate,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	Height      *int64     `json:"height,omitempty"`
	MimeType    *string    `json:"mime_type,omitempty"`
	Role        *string    `json:"role,omitempty"`
	URL         string     `json:"url"`
	Watermarked *bool      `json:"watermarked,omitempty"`
	Width       *int64     `json:"width,omitempty"`
}

type PostMetrics struct {
	Comments *int64 `json:"comments"`
	Likes    *int64 `json:"likes"`
	Reposts  *int64 `json:"reposts"`
	Saves    *int64 `json:"saves"`
	Shares   *int64 `json:"shares"`
	Views    *int64 `json:"views"`
}

type PostMusic struct {
	Album        *string          `json:"album"`
	Artist       *PostMusicArtist `json:"artist"`
	Artwork      *MediaReference  `json:"artwork"`
	Audio        *MediaReference  `json:"audio"`
	Duration     *float64         `json:"duration"`
	ID           string           `json:"id"`
	IsCommercial *bool            `json:"is_commercial"`
	IsExplicit   *bool            `json:"is_explicit"`
	IsOriginal   *bool            `json:"is_original"`
	Title        *string          `json:"title"`
}

type PostMusicArtist struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type Profile = ProfileCore

type ProfileCore struct {
	AccountType *string         `json:"account_type"`
	Avatar      *MediaReference `json:"avatar"`
	Bio         string          `json:"bio"`
	Category    *string         `json:"category"`
	DisplayName string          `json:"display_name"`
	ExternalURL *string         `json:"external_url"`
	Handle      string          `json:"handle"`
	ID          string          `json:"id"`
	IsBusiness  bool            `json:"is_business"`
	IsPrivate   bool            `json:"is_private"`
	IsVerified  bool            `json:"is_verified"`
	Metrics     ProfileMetrics  `json:"metrics"`
}

type ProfileLink struct {
	Title *string `json:"title"`
	URL   string  `json:"url"`
}

type ProfileMetrics struct {
	Followers *int64 `json:"followers"`
	Following *int64 `json:"following"`
	Posts     *int64 `json:"posts"`
}

type SearchResultMetrics struct {
	Comments  *int64 `json:"comments,omitempty"`
	Followers *int64 `json:"followers,omitempty"`
	Likes     *int64 `json:"likes,omitempty"`
	Posts     *int64 `json:"posts,omitempty"`
	Shares    *int64 `json:"shares,omitempty"`
	Views     *int64 `json:"views,omitempty"`
}

type StoryLink struct {
	DisplayURL *string  `json:"display_url,omitempty"`
	Height     *float64 `json:"height,omitempty"`
	Rotation   *float64 `json:"rotation,omitempty"`
	Title      *string  `json:"title,omitempty"`
	URL        string   `json:"url"`
	Width      *float64 `json:"width,omitempty"`
	X          *float64 `json:"x,omitempty"`
	Y          *float64 `json:"y,omitempty"`
}

type StorySticker struct {
	Height   *float64   `json:"height,omitempty"`
	ID       *string    `json:"id,omitempty"`
	Link     *StoryLink `json:"link,omitempty"`
	Rotation *float64   `json:"rotation,omitempty"`
	Type     *string    `json:"type,omitempty"`
	Width    *float64   `json:"width,omitempty"`
	X        *float64   `json:"x,omitempty"`
	Y        *float64   `json:"y,omitempty"`
}

type SuccessEnvelope struct {
	CapturedAt time.Time `json:"captured_at"`
	Data       any       `json:"data"`
	Meta       *struct {
		Cursors struct {
			Next *string `json:"next"`
		} `json:"cursors"`
	} `json:"meta,omitempty"`
	Platform string `json:"platform"`
	Resource string `json:"resource"`
	Source   string `json:"source"`
}

type TestDataCatalog struct {
	ChangeNotes        []string            `json:"changeNotes"`
	ContentHash        string              `json:"contentHash"`
	DatasetVersion     string              `json:"datasetVersion"`
	Entries            []TestDataEntry     `json:"entries"`
	MediaProvenanceURL string              `json:"mediaProvenanceUrl"`
	Operations         []TestDataOperation `json:"operations"`
	Synthetic          bool                `json:"synthetic"`
}

type TestDataCatalogEnvelope struct {
	Data TestDataCatalog `json:"data"`
}

type TestDataEntry struct {
	DatasetVersion string                 `json:"datasetVersion"`
	Description    string                 `json:"description"`
	Expected       TestDataExpectedResult `json:"expected"`
	ID             string                 `json:"id"`
	Inputs         map[string]any         `json:"inputs"`
	Label          string                 `json:"label"`
	OperationIDs   []string               `json:"operationIds"`
	Platform       string                 `json:"platform"`
	Relationships  []TestDataRelationship `json:"relationships"`
	Resource       string                 `json:"resource"`
	Synthetic      bool                   `json:"synthetic"`
	Traits         []string               `json:"traits"`
}

type TestDataEntryEnvelope struct {
	Data TestDataEntry `json:"data"`
}

type TestDataExpectedResult struct {
	ErrorCode *string `json:"errorCode,omitempty"`
	Status    int64   `json:"status"`
}

type TestDataOperation struct {
	Description  string   `json:"description"`
	ID           string   `json:"id"`
	InputFields  []string `json:"inputFields"`
	Locators     []string `json:"locators"`
	Method       string   `json:"method"`
	Paginated    bool     `json:"paginated"`
	Path         string   `json:"path"`
	Platform     string   `json:"platform"`
	PublicSchema string   `json:"publicSchema"`
	Resource     string   `json:"resource"`
	Summary      string   `json:"summary"`
	ToolName     string   `json:"toolName"`
}

type TestDataRelationship struct {
	EntryID string `json:"entryId"`
	Type    string `json:"type"`
}

type TikTokComment struct {
	CommentCore
}

type TikTokEffect struct {
	CreatedAt    *time.Time      `json:"created_at,omitempty"`
	Description  *string         `json:"description,omitempty"`
	ID           string          `json:"id"`
	Image        *MediaReference `json:"image,omitempty"`
	IsCommercial *bool           `json:"is_commercial,omitempty"`
	Name         *string         `json:"name,omitempty"`
	PostCount    *int64          `json:"post_count,omitempty"`
	Type         *string         `json:"type,omitempty"`
	URL          *string         `json:"url,omitempty"`
	ViewCount    *int64          `json:"view_count,omitempty"`
}

type TikTokEntity struct {
	EntityCore
}

type TikTokInsight struct {
	GrowthRate      *float64 `json:"growth_rate,omitempty"`
	ID              string   `json:"id"`
	Keyword         *string  `json:"keyword,omitempty"`
	Period          *string  `json:"period,omitempty"`
	PostCount       *int64   `json:"post_count,omitempty"`
	Rank            *int64   `json:"rank,omitempty"`
	RelatedKeywords []string `json:"related_keywords"`
	SearchVolume    *int64   `json:"search_volume,omitempty"`
	Title           *string  `json:"title,omitempty"`
	Trend           *string  `json:"trend,omitempty"`
	ViewCount       *int64   `json:"view_count,omitempty"`
}

type TikTokLiveRanking struct {
	ID    string           `json:"id"`
	Rank  *int64           `json:"rank,omitempty"`
	Score *int64           `json:"score,omitempty"`
	User  *EntityReference `json:"user,omitempty"`
}

type TikTokLiveRoom struct {
	Cover        *MediaReference  `json:"cover,omitempty"`
	EndedAt      *time.Time       `json:"ended_at,omitempty"`
	Host         *EntityReference `json:"host,omitempty"`
	ID           string           `json:"id"`
	LikeCount    *int64           `json:"like_count,omitempty"`
	ProductCount *int64           `json:"product_count,omitempty"`
	StartedAt    *time.Time       `json:"started_at,omitempty"`
	Status       *string          `json:"status,omitempty"`
	Title        *string          `json:"title,omitempty"`
	URL          *string          `json:"url,omitempty"`
	ViewerCount  *int64           `json:"viewer_count,omitempty"`
}

type TikTokOption struct {
	Description *string `json:"description,omitempty"`
	ID          string  `json:"id"`
	IsSelected  *bool   `json:"is_selected,omitempty"`
	Label       *string `json:"label,omitempty"`
	Position    *int64  `json:"position,omitempty"`
	Value       *string `json:"value,omitempty"`
}

type TikTokPlaylist struct {
	Cover       *MediaReference  `json:"cover,omitempty"`
	CreatedAt   *time.Time       `json:"created_at,omitempty"`
	Description *string          `json:"description,omitempty"`
	ID          string           `json:"id"`
	Name        *string          `json:"name,omitempty"`
	Owner       *EntityReference `json:"owner,omitempty"`
	PlayCount   *int64           `json:"play_count,omitempty"`
	PostCount   *int64           `json:"post_count,omitempty"`
	UpdatedAt   *time.Time       `json:"updated_at,omitempty"`
	URL         *string          `json:"url,omitempty"`
}

type TikTokPost struct {
	PostCore
	Collaborators     []PostAuthor        `json:"collaborators"`
	Extended          *TikTokPostExtended `json:"extended,omitempty"`
	IsAd              *bool               `json:"is_ad"`
	IsPaidPartnership *bool               `json:"is_paid_partnership"`
	Location          *PostLocation       `json:"location"`
	Metrics           TikTokPostMetrics   `json:"metrics"`
	Music             *PostMusic          `json:"music"`
	Sponsors          []PostAuthor        `json:"sponsors"`
	TaggedUsers       []PostAuthor        `json:"tagged_users"`
}

type TikTokPostExtended struct {
	AiLabelType          *int64 `json:"ai_label_type,omitempty"`
	AllowsDuet           *bool  `json:"allows_duet,omitempty"`
	AllowsStitch         *bool  `json:"allows_stitch,omitempty"`
	IsAiGenerated        *bool  `json:"is_ai_generated,omitempty"`
	IsDownloadable       *bool  `json:"is_downloadable,omitempty"`
	UsesPromotionalMusic *bool  `json:"uses_promotional_music,omitempty"`
}

type TikTokPostMetrics struct {
	PostMetrics
	Downloads *int64 `json:"downloads"`
}

type TikTokProfile struct {
	ProfileCore
	Extended *TikTokProfileExtended `json:"extended,omitempty"`
}

type TikTokProfileExtended struct {
	HasCommerce       *bool   `json:"has_commerce"`
	IsProAccount      *bool   `json:"is_pro_account"`
	VerificationLabel *string `json:"verification_label"`
	VerificationType  *int64  `json:"verification_type"`
}

type TikTokQRCode struct {
	ExpiresAt *time.Time      `json:"expires_at,omitempty"`
	Height    *int64          `json:"height,omitempty"`
	ID        string          `json:"id"`
	Image     *MediaReference `json:"image,omitempty"`
	URL       *string         `json:"url,omitempty"`
	Width     *int64          `json:"width,omitempty"`
}

type TikTokSearchResult struct {
	Author      *EntityReference     `json:"author,omitempty"`
	Description *string              `json:"description,omitempty"`
	Handle      *string              `json:"handle,omitempty"`
	ID          string               `json:"id"`
	Image       *MediaReference      `json:"image,omitempty"`
	Metrics     *SearchResultMetrics `json:"metrics,omitempty"`
	Title       *string              `json:"title,omitempty"`
	Type        *string              `json:"type,omitempty"`
	URL         *string              `json:"url,omitempty"`
}

type TikTokShopCategory struct {
	ID           string  `json:"id"`
	Name         *string `json:"name,omitempty"`
	ParentID     *string `json:"parent_id,omitempty"`
	ProductCount *int64  `json:"product_count,omitempty"`
}

type TikTokShopProduct struct {
	Description   *string          `json:"description,omitempty"`
	Discount      *string          `json:"discount,omitempty"`
	ID            string           `json:"id"`
	Images        []MediaReference `json:"images"`
	Name          *string          `json:"name,omitempty"`
	OriginalPrice *Money           `json:"original_price,omitempty"`
	Price         *Money           `json:"price,omitempty"`
	Rating        *float64         `json:"rating,omitempty"`
	ReviewCount   *int64           `json:"review_count,omitempty"`
	Seller        *EntityReference `json:"seller,omitempty"`
	Sold          *int64           `json:"sold,omitempty"`
	Stock         *int64           `json:"stock,omitempty"`
	URL           *string          `json:"url,omitempty"`
}

type TikTokShopReview struct {
	Author      *EntityReference `json:"author,omitempty"`
	Helpful     *int64           `json:"helpful,omitempty"`
	ID          string           `json:"id"`
	Images      []MediaReference `json:"images"`
	PublishedAt *time.Time       `json:"published_at,omitempty"`
	Rating      *float64         `json:"rating,omitempty"`
	Text        *string          `json:"text,omitempty"`
}

type TikTokShopSeller struct {
	Description *string         `json:"description,omitempty"`
	Followers   *int64          `json:"followers,omitempty"`
	Handle      *string         `json:"handle,omitempty"`
	ID          string          `json:"id"`
	Image       *MediaReference `json:"image,omitempty"`
	Name        *string         `json:"name,omitempty"`
	Products    *int64          `json:"products,omitempty"`
	Rating      *float64        `json:"rating,omitempty"`
	Region      *string         `json:"region,omitempty"`
	Sold        *int64          `json:"sold,omitempty"`
	URL         *string         `json:"url,omitempty"`
}

type TikTokSuggestion struct {
	Highlighted *string          `json:"highlighted,omitempty"`
	ID          string           `json:"id"`
	Score       *float64         `json:"score,omitempty"`
	Text        string           `json:"text"`
	Type        *string          `json:"type,omitempty"`
	User        *EntityReference `json:"user,omitempty"`
}

type TrendingCategory struct {
	Description *string `json:"description"`
	ID          string  `json:"id"`
	Metrics     struct {
		Posts *int64 `json:"posts"`
		Views *int64 `json:"views"`
	} `json:"metrics"`
	Name string `json:"name"`
}

type TwitterComment struct {
	CommentCore
}

type TwitterEntity struct {
	EntityCore
}

type TwitterList struct {
	CreatedAt   *time.Time `json:"created_at"`
	Description *string    `json:"description"`
	ID          string     `json:"id"`
	IsPrivate   *bool      `json:"is_private"`
	Metrics     struct {
		Followers *int64 `json:"followers"`
		Members   *int64 `json:"members"`
	} `json:"metrics"`
	Name  string      `json:"name"`
	Owner *PostAuthor `json:"owner"`
}

type TwitterPost struct {
	PostCore
	Extended     *TwitterPostExtended `json:"extended,omitempty"`
	Metrics      TwitterPostMetrics   `json:"metrics"`
	QuotedPost   *TwitterPost         `json:"quoted_post,omitempty"`
	RepostedPost *TwitterPost         `json:"reposted_post,omitempty"`
}

type TwitterPostExtended struct {
	ConversationID  *string `json:"conversation_id,omitempty"`
	InReplyToPostID *string `json:"in_reply_to_post_id,omitempty"`
	InReplyToUserID *string `json:"in_reply_to_user_id,omitempty"`
	Language        *string `json:"language,omitempty"`
	QuotedPostID    *string `json:"quoted_post_id,omitempty"`
	RepostedPostID  *string `json:"reposted_post_id,omitempty"`
}

type TwitterPostMetrics struct {
	PostMetrics
	Bookmarks *int64 `json:"bookmarks"`
	Quotes    *int64 `json:"quotes"`
}

type TwitterProfile struct {
	ProfileCore
	Extended *TwitterProfileExtended `json:"extended,omitempty"`
}

type TwitterProfileExtended struct {
	Banner            *MediaReference `json:"banner"`
	CreatedAt         *time.Time      `json:"created_at"`
	Likes             *int64          `json:"likes"`
	Location          *string         `json:"location"`
	Media             *int64          `json:"media"`
	PinnedPostIDs     []string        `json:"pinned_post_ids"`
	WithheldCountries []string        `json:"withheld_countries"`
}

type TwitterSuggestion struct {
	Highlighted *string          `json:"highlighted,omitempty"`
	ID          string           `json:"id"`
	Score       *float64         `json:"score,omitempty"`
	Text        string           `json:"text"`
	Type        *string          `json:"type,omitempty"`
	User        *EntityReference `json:"user,omitempty"`
}
