// Code generated by internal/cmd/generate. DO NOT EDIT.

package openhandle

import "time"

type Comment = CommentCore

type CommentCore struct {
	Author              PostAuthor     `json:"author"`
	ID                  string         `json:"id"`
	IsLikedByPostAuthor *bool          `json:"isLikedByPostAuthor"`
	IsPinned            *bool          `json:"isPinned"`
	Media               []PostMedia    `json:"media"`
	Metrics             CommentMetrics `json:"metrics"`
	ParentID            *string        `json:"parentId"`
	PinnedPosition      *int64         `json:"pinnedPosition"`
	PublishedAt         time.Time      `json:"publishedAt"`
	ReplyPreview        []Comment      `json:"replyPreview,omitempty"`
	Text                string         `json:"text"`
	ThreadRootID        *string        `json:"threadRootId"`
}

type CommentMetrics struct {
	Bookmarks *int64 `json:"bookmarks"`
	Likes     *int64 `json:"likes"`
	Quotes    *int64 `json:"quotes"`
	Replies   *int64 `json:"replies"`
	Reposts   *int64 `json:"reposts"`
	Views     *int64 `json:"views"`
}

type Entity = EntityCore

type EntityCore struct {
	Attributes  map[string]any  `json:"attributes"`
	Description *string         `json:"description"`
	Handle      *string         `json:"handle"`
	ID          string          `json:"id"`
	Image       *MediaReference `json:"image"`
	Kind        string          `json:"kind"`
	Metrics     map[string]any  `json:"metrics"`
	Name        *string         `json:"name"`
	URL         *string         `json:"url"`
}

type EntityReference struct {
	Handle *string         `json:"handle,omitempty"`
	ID     string          `json:"id"`
	Image  *MediaReference `json:"image,omitempty"`
	Name   *string         `json:"name,omitempty"`
	URL    *string         `json:"url,omitempty"`
}

type ErrorEnvelope struct {
	Error struct {
		Code      string         `json:"code"`
		Details   map[string]any `json:"details,omitempty"`
		Message   string         `json:"message"`
		RequestID string         `json:"requestId"`
		Retryable bool           `json:"retryable"`
	} `json:"error"`
}

type Hashtag struct {
	Description *string         `json:"description"`
	ID          string          `json:"id"`
	Image       *MediaReference `json:"image"`
	Metrics     struct {
		Posts *int64 `json:"posts"`
		Views *int64 `json:"views"`
	} `json:"metrics"`
	Name string `json:"name"`
}

type InstagramClipMetadata struct {
	Author      *EntityReference `json:"author,omitempty"`
	Caption     *string          `json:"caption,omitempty"`
	Duration    *float64         `json:"duration,omitempty"`
	Height      *int64           `json:"height,omitempty"`
	ID          string           `json:"id"`
	Media       []PostMedia      `json:"media"`
	Music       *PostMusic       `json:"music,omitempty"`
	PlayCount   *int64           `json:"playCount,omitempty"`
	PublishedAt *time.Time       `json:"publishedAt,omitempty"`
	Title       *string          `json:"title,omitempty"`
	ViewCount   *int64           `json:"viewCount,omitempty"`
	Width       *int64           `json:"width,omitempty"`
}

type InstagramComment struct {
	CommentCore
}

type InstagramCommentMetadata struct {
	CanComment       *bool  `json:"canComment,omitempty"`
	CanViewMore      *bool  `json:"canViewMore,omitempty"`
	CommentCount     *int64 `json:"commentCount,omitempty"`
	CommentsDisabled *bool  `json:"commentsDisabled,omitempty"`
	ID               string `json:"id"`
	PreviewCount     *int64 `json:"previewCount,omitempty"`
}

type InstagramCommentModeration struct {
	ID          string   `json:"id"`
	IsBullying  *bool    `json:"isBullying,omitempty"`
	IsOffensive *bool    `json:"isOffensive,omitempty"`
	IsSpam      *bool    `json:"isSpam,omitempty"`
	Reasons     []string `json:"reasons"`
	Score       *float64 `json:"score,omitempty"`
	Text        *string  `json:"text,omitempty"`
}

type InstagramEntity struct {
	EntityCore
}

type InstagramHighlight struct {
	Cover     *MediaReference  `json:"cover,omitempty"`
	ID        string           `json:"id"`
	ItemCount *int64           `json:"itemCount,omitempty"`
	Items     []InstagramStory `json:"items"`
	Owner     *EntityReference `json:"owner,omitempty"`
	Title     *string          `json:"title,omitempty"`
}

type InstagramLocationGuide struct {
	Author      *EntityReference `json:"author,omitempty"`
	Description *string          `json:"description,omitempty"`
	ID          string           `json:"id"`
	Image       *MediaReference  `json:"image,omitempty"`
	ItemCount   *int64           `json:"itemCount,omitempty"`
	Location    *PostLocation    `json:"location,omitempty"`
	Title       *string          `json:"title,omitempty"`
	URL         *string          `json:"url,omitempty"`
}

type InstagramMusicStream struct {
	Bitrate   *int64     `json:"bitrate,omitempty"`
	Duration  *float64   `json:"duration,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	ID        string     `json:"id"`
	MimeType  *string    `json:"mimeType,omitempty"`
	Page      *int64     `json:"page,omitempty"`
	URL       *string    `json:"url,omitempty"`
}

type InstagramOEmbed struct {
	AuthorName   *string         `json:"authorName,omitempty"`
	AuthorURL    *string         `json:"authorUrl,omitempty"`
	Height       *int64          `json:"height,omitempty"`
	Html         *string         `json:"html,omitempty"`
	ID           string          `json:"id"`
	ProviderName *string         `json:"providerName,omitempty"`
	ProviderURL  *string         `json:"providerUrl,omitempty"`
	Thumbnail    *MediaReference `json:"thumbnail,omitempty"`
	Title        *string         `json:"title,omitempty"`
	Type         *string         `json:"type,omitempty"`
	URL          *string         `json:"url,omitempty"`
	Width        *int64          `json:"width,omitempty"`
}

type InstagramPlayCountBreakdown struct {
	Facebook  *int64 `json:"facebook"`
	Instagram *int64 `json:"instagram"`
}

type InstagramPost struct {
	PostCore
	Collaborators     []PostAuthor           `json:"collaborators"`
	Extended          *InstagramPostExtended `json:"extended,omitempty"`
	IsAd              *bool                  `json:"isAd"`
	IsPaidPartnership *bool                  `json:"isPaidPartnership"`
	Location          *PostLocation          `json:"location"`
	Metrics           InstagramPostMetrics   `json:"metrics"`
	Music             *PostMusic             `json:"music"`
	Shortcode         *string                `json:"shortcode"`
	Sponsors          []PostAuthor           `json:"sponsors"`
	TaggedUsers       []PostAuthor           `json:"taggedUsers"`
}

type InstagramPostExtended struct {
	AccessibilityCaption *string `json:"accessibilityCaption"`
	LikeCountsHidden     *bool   `json:"likeCountsHidden"`
	ProductType          *string `json:"productType"`
}

type InstagramPostInsight struct {
	AverageWatchTime *float64 `json:"averageWatchTime,omitempty"`
	Comments         *int64   `json:"comments,omitempty"`
	Follows          *int64   `json:"follows,omitempty"`
	ID               string   `json:"id"`
	Impressions      *int64   `json:"impressions,omitempty"`
	Interactions     *int64   `json:"interactions,omitempty"`
	Likes            *int64   `json:"likes,omitempty"`
	Plays            *int64   `json:"plays,omitempty"`
	ProfileVisits    *int64   `json:"profileVisits,omitempty"`
	Reach            *int64   `json:"reach,omitempty"`
	Saves            *int64   `json:"saves,omitempty"`
	Shares           *int64   `json:"shares,omitempty"`
	Views            *int64   `json:"views,omitempty"`
	WatchTime        *float64 `json:"watchTime,omitempty"`
}

type InstagramPostMetrics struct {
	PostMetrics
	PlayCountBreakdown *InstagramPlayCountBreakdown `json:"playCountBreakdown,omitempty"`
}

type InstagramProfile struct {
	ProfileCore
	Extended *InstagramProfileExtended `json:"extended,omitempty"`
}

type InstagramProfileAbout struct {
	Bio                 *string    `json:"bio,omitempty"`
	Category            *string    `json:"category,omitempty"`
	Country             *string    `json:"country,omitempty"`
	DisplayName         *string    `json:"displayName,omitempty"`
	ExternalURL         *string    `json:"externalUrl,omitempty"`
	FormerUsernameCount *int64     `json:"formerUsernameCount,omitempty"`
	Handle              *string    `json:"handle,omitempty"`
	ID                  string     `json:"id"`
	IsBusiness          *bool      `json:"isBusiness,omitempty"`
	IsPrivate           *bool      `json:"isPrivate,omitempty"`
	IsVerified          *bool      `json:"isVerified,omitempty"`
	JoinedAt            *time.Time `json:"joinedAt,omitempty"`
}

type InstagramProfileExtended struct {
	AccountTypeCode        *int64        `json:"accountTypeCode"`
	AddressStreet          *string       `json:"addressStreet"`
	BioLinks               []ProfileLink `json:"bioLinks"`
	BusinessContactMethod  *string       `json:"businessContactMethod"`
	City                   *string       `json:"city"`
	Latitude               *float64      `json:"latitude"`
	Longitude              *float64      `json:"longitude"`
	PostalCode             *string       `json:"postalCode"`
	PublicEmail            *string       `json:"publicEmail"`
	PublicPhoneCountryCode *string       `json:"publicPhoneCountryCode"`
	PublicPhoneNumber      *string       `json:"publicPhoneNumber"`
}

type InstagramProfileSummary struct {
	Avatar      *MediaReference `json:"avatar,omitempty"`
	Bio         *string         `json:"bio,omitempty"`
	Category    *string         `json:"category,omitempty"`
	DisplayName *string         `json:"displayName,omitempty"`
	Followers   *int64          `json:"followers,omitempty"`
	Handle      *string         `json:"handle,omitempty"`
	ID          string          `json:"id"`
	IsPrivate   *bool           `json:"isPrivate,omitempty"`
	IsVerified  *bool           `json:"isVerified,omitempty"`
	URL         *string         `json:"url,omitempty"`
}

type InstagramSearchResult struct {
	Author      *EntityReference     `json:"author,omitempty"`
	Description *string              `json:"description,omitempty"`
	Handle      *string              `json:"handle,omitempty"`
	ID          string               `json:"id"`
	Image       *MediaReference      `json:"image,omitempty"`
	Metrics     *SearchResultMetrics `json:"metrics,omitempty"`
	Title       *string              `json:"title,omitempty"`
	Type        *string              `json:"type,omitempty"`
	URL         *string              `json:"url,omitempty"`
}

type InstagramStory struct {
	Author        *EntityReference  `json:"author,omitempty"`
	CanQuickReply *bool             `json:"canQuickReply,omitempty"`
	CanReply      *bool             `json:"canReply,omitempty"`
	CanReshare    *bool             `json:"canReshare,omitempty"`
	ExpiresAt     *time.Time        `json:"expiresAt,omitempty"`
	Hashtags      []string          `json:"hashtags"`
	ID            string            `json:"id"`
	Links         []StoryLink       `json:"links"`
	Locations     []PostLocation    `json:"locations"`
	Media         []PostMedia       `json:"media"`
	Mentions      []EntityReference `json:"mentions"`
	PublishedAt   *time.Time        `json:"publishedAt,omitempty"`
	Shortcode     *string           `json:"shortcode,omitempty"`
	Stickers      []StorySticker    `json:"stickers"`
	Type          *string           `json:"type,omitempty"`
}

type InstagramTemplate struct {
	Author      *EntityReference `json:"author,omitempty"`
	Description *string          `json:"description,omitempty"`
	Duration    *float64         `json:"duration,omitempty"`
	ID          string           `json:"id"`
	Media       []PostMedia      `json:"media"`
	Name        *string          `json:"name,omitempty"`
	Type        *string          `json:"type,omitempty"`
	URL         *string          `json:"url,omitempty"`
}

type Location struct {
	Address     *string  `json:"address"`
	Category    *string  `json:"category"`
	City        *string  `json:"city"`
	CountryCode *string  `json:"countryCode"`
	ID          string   `json:"id"`
	Latitude    *float64 `json:"latitude"`
	Longitude   *float64 `json:"longitude"`
	Name        string   `json:"name"`
	Phone       *string  `json:"phone"`
	PostalCode  *string  `json:"postalCode"`
	Region      *string  `json:"region"`
	Website     *string  `json:"website"`
}

type MediaReference struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	URL       string     `json:"url"`
}

type MessageEnvelope struct {
	Message string `json:"message"`
}

type Music struct {
	Album        *string          `json:"album"`
	Artist       *PostMusicArtist `json:"artist"`
	Artwork      *MediaReference  `json:"artwork"`
	Audio        *MediaReference  `json:"audio"`
	Duration     *float64         `json:"duration"`
	ID           string           `json:"id"`
	IsCommercial *bool            `json:"isCommercial"`
	IsExplicit   *bool            `json:"isExplicit"`
	IsOriginal   *bool            `json:"isOriginal"`
	Metrics      struct {
		Posts *int64 `json:"posts"`
	} `json:"metrics"`
	Title string `json:"title"`
}

type PostAuthor struct {
	Avatar      *MediaReference `json:"avatar"`
	DisplayName *string         `json:"displayName"`
	Handle      string          `json:"handle"`
	ID          string          `json:"id"`
	IsVerified  *bool           `json:"isVerified"`
}

type PostCore struct {
	Author           PostAuthor  `json:"author"`
	Caption          *string     `json:"caption"`
	CommentsDisabled *bool       `json:"commentsDisabled"`
	Format           string      `json:"format"`
	Hashtags         []string    `json:"hashtags"`
	ID               string      `json:"id"`
	Media            []PostMedia `json:"media"`
	Mentions         []string    `json:"mentions"`
	PublishedAt      time.Time   `json:"publishedAt"`
	Title            *string     `json:"title"`
	Type             string      `json:"type"`
	URL              string      `json:"url"`
}

type PostLocation struct {
	Address     *string  `json:"address"`
	Category    *string  `json:"category"`
	City        *string  `json:"city"`
	CountryCode *string  `json:"countryCode"`
	ID          *string  `json:"id"`
	Latitude    *float64 `json:"latitude"`
	Longitude   *float64 `json:"longitude"`
	Name        *string  `json:"name"`
	Phone       *string  `json:"phone"`
	PostalCode  *string  `json:"postalCode"`
	Region      *string  `json:"region"`
	Website     *string  `json:"website"`
}

type PostMedia struct {
	AltText   *string            `json:"altText,omitempty"`
	Duration  *float64           `json:"duration,omitempty"`
	ExpiresAt *time.Time         `json:"expiresAt,omitempty"`
	Height    *int64             `json:"height,omitempty"`
	ID        *string            `json:"id,omitempty"`
	Thumbnail *MediaReference    `json:"thumbnail,omitempty"`
	Type      string             `json:"type"`
	URL       string             `json:"url"`
	Variants  []PostMediaVariant `json:"variants,omitempty"`
	Width     *int64             `json:"width,omitempty"`
}

type PostMediaVariant struct {
	Bitrate     *int64     `json:"bitrate,omitempty"`
	ExpiresAt   *time.Time `json:"expiresAt,omitempty"`
	Height      *int64     `json:"height,omitempty"`
	MimeType    *string    `json:"mimeType,omitempty"`
	Role        *string    `json:"role,omitempty"`
	URL         string     `json:"url"`
	Watermarked *bool      `json:"watermarked,omitempty"`
	Width       *int64     `json:"width,omitempty"`
}

type PostMetrics struct {
	Comments *int64 `json:"comments"`
	Likes    *int64 `json:"likes"`
	Reposts  *int64 `json:"reposts"`
	Saves    *int64 `json:"saves"`
	Shares   *int64 `json:"shares"`
	Views    *int64 `json:"views"`
}

type PostMusic struct {
	Album        *string          `json:"album"`
	Artist       *PostMusicArtist `json:"artist"`
	Artwork      *MediaReference  `json:"artwork"`
	Audio        *MediaReference  `json:"audio"`
	Duration     *float64         `json:"duration"`
	ID           string           `json:"id"`
	IsCommercial *bool            `json:"isCommercial"`
	IsExplicit   *bool            `json:"isExplicit"`
	IsOriginal   *bool            `json:"isOriginal"`
	Title        *string          `json:"title"`
}

type PostMusicArtist struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}

type Profile = ProfileCore

type ProfileCore struct {
	AccountType *string         `json:"accountType"`
	Avatar      *MediaReference `json:"avatar"`
	Bio         string          `json:"bio"`
	Category    *string         `json:"category"`
	DisplayName string          `json:"displayName"`
	ExternalURL *string         `json:"externalUrl"`
	Handle      string          `json:"handle"`
	ID          string          `json:"id"`
	IsBusiness  bool            `json:"isBusiness"`
	IsPrivate   bool            `json:"isPrivate"`
	IsVerified  bool            `json:"isVerified"`
	Metrics     ProfileMetrics  `json:"metrics"`
}

type ProfileLink struct {
	Title *string `json:"title"`
	URL   string  `json:"url"`
}

type ProfileMetrics struct {
	Followers *int64 `json:"followers"`
	Following *int64 `json:"following"`
	Posts     *int64 `json:"posts"`
}

type SearchResultMetrics struct {
	Comments  *int64 `json:"comments,omitempty"`
	Followers *int64 `json:"followers,omitempty"`
	Likes     *int64 `json:"likes,omitempty"`
	Posts     *int64 `json:"posts,omitempty"`
	Shares    *int64 `json:"shares,omitempty"`
	Views     *int64 `json:"views,omitempty"`
}

type StoryLink struct {
	DisplayURL *string  `json:"displayUrl,omitempty"`
	Height     *float64 `json:"height,omitempty"`
	Rotation   *float64 `json:"rotation,omitempty"`
	Title      *string  `json:"title,omitempty"`
	URL        string   `json:"url"`
	Width      *float64 `json:"width,omitempty"`
	X          *float64 `json:"x,omitempty"`
	Y          *float64 `json:"y,omitempty"`
}

type StorySticker struct {
	Height   *float64   `json:"height,omitempty"`
	ID       *string    `json:"id,omitempty"`
	Link     *StoryLink `json:"link,omitempty"`
	Rotation *float64   `json:"rotation,omitempty"`
	Type     *string    `json:"type,omitempty"`
	Width    *float64   `json:"width,omitempty"`
	X        *float64   `json:"x,omitempty"`
	Y        *float64   `json:"y,omitempty"`
}

type SuccessEnvelope struct {
	CapturedAt time.Time `json:"capturedAt"`
	Data       any       `json:"data"`
	Meta       *struct {
		Cursors struct {
			Next *string `json:"next"`
		} `json:"cursors"`
	} `json:"meta,omitempty"`
	Platform string `json:"platform"`
	Resource string `json:"resource"`
	Source   string `json:"source"`
}

type TestDataCatalog struct {
	ChangeNotes        []string            `json:"changeNotes"`
	ContentHash        string              `json:"contentHash"`
	DatasetVersion     string              `json:"datasetVersion"`
	Entries            []TestDataEntry     `json:"entries"`
	MediaProvenanceURL string              `json:"mediaProvenanceUrl"`
	Operations         []TestDataOperation `json:"operations"`
	Synthetic          bool                `json:"synthetic"`
}

type TestDataCatalogEnvelope struct {
	Data TestDataCatalog `json:"data"`
}

type TestDataEntry struct {
	DatasetVersion string                 `json:"datasetVersion"`
	Description    string                 `json:"description"`
	Expected       TestDataExpectedResult `json:"expected"`
	ID             string                 `json:"id"`
	Inputs         map[string]any         `json:"inputs"`
	Label          string                 `json:"label"`
	OperationIDs   []string               `json:"operationIds"`
	Platform       string                 `json:"platform"`
	Relationships  []TestDataRelationship `json:"relationships"`
	Resource       string                 `json:"resource"`
	Synthetic      bool                   `json:"synthetic"`
	Traits         []string               `json:"traits"`
}

type TestDataEntryEnvelope struct {
	Data TestDataEntry `json:"data"`
}

type TestDataExpectedResult struct {
	ErrorCode *string `json:"errorCode,omitempty"`
	Status    int64   `json:"status"`
}

type TestDataOperation struct {
	Description  string   `json:"description"`
	ID           string   `json:"id"`
	InputFields  []string `json:"inputFields"`
	Locators     []string `json:"locators"`
	Method       string   `json:"method"`
	Paginated    bool     `json:"paginated"`
	Path         string   `json:"path"`
	Platform     string   `json:"platform"`
	PublicSchema string   `json:"publicSchema"`
	Resource     string   `json:"resource"`
	Summary      string   `json:"summary"`
	ToolName     string   `json:"toolName"`
}

type TestDataRelationship struct {
	EntryID string `json:"entryId"`
	Type    string `json:"type"`
}

type TikTokComment struct {
	CommentCore
}

type TikTokEffect struct {
	CreatedAt    *time.Time      `json:"createdAt,omitempty"`
	Description  *string         `json:"description,omitempty"`
	ID           string          `json:"id"`
	Image        *MediaReference `json:"image,omitempty"`
	IsCommercial *bool           `json:"isCommercial,omitempty"`
	Name         *string         `json:"name,omitempty"`
	PostCount    *int64          `json:"postCount,omitempty"`
	Type         *string         `json:"type,omitempty"`
	URL          *string         `json:"url,omitempty"`
	ViewCount    *int64          `json:"viewCount,omitempty"`
}

type TikTokEntity struct {
	EntityCore
}

type TikTokPlaylist struct {
	Cover       *MediaReference  `json:"cover,omitempty"`
	CreatedAt   *time.Time       `json:"createdAt,omitempty"`
	Description *string          `json:"description,omitempty"`
	ID          string           `json:"id"`
	Name        *string          `json:"name,omitempty"`
	Owner       *EntityReference `json:"owner,omitempty"`
	PlayCount   *int64           `json:"playCount,omitempty"`
	PostCount   *int64           `json:"postCount,omitempty"`
	UpdatedAt   *time.Time       `json:"updatedAt,omitempty"`
	URL         *string          `json:"url,omitempty"`
}

type TikTokPost struct {
	PostCore
	Collaborators     []PostAuthor        `json:"collaborators"`
	Extended          *TikTokPostExtended `json:"extended,omitempty"`
	IsAd              *bool               `json:"isAd"`
	IsPaidPartnership *bool               `json:"isPaidPartnership"`
	Location          *PostLocation       `json:"location"`
	Metrics           TikTokPostMetrics   `json:"metrics"`
	Music             *PostMusic          `json:"music"`
	Sponsors          []PostAuthor        `json:"sponsors"`
	TaggedUsers       []PostAuthor        `json:"taggedUsers"`
}

type TikTokPostExtended struct {
	AiLabelType          *int64 `json:"aiLabelType,omitempty"`
	AllowsDuet           *bool  `json:"allowsDuet,omitempty"`
	AllowsStitch         *bool  `json:"allowsStitch,omitempty"`
	IsAiGenerated        *bool  `json:"isAiGenerated,omitempty"`
	IsDownloadable       *bool  `json:"isDownloadable,omitempty"`
	UsesPromotionalMusic *bool  `json:"usesPromotionalMusic,omitempty"`
}

type TikTokPostMetrics struct {
	PostMetrics
	Downloads *int64 `json:"downloads"`
}

type TikTokProfile struct {
	ProfileCore
	Extended *TikTokProfileExtended `json:"extended,omitempty"`
}

type TikTokProfileExtended struct {
	HasCommerce       *bool   `json:"hasCommerce"`
	IsProAccount      *bool   `json:"isProAccount"`
	VerificationLabel *string `json:"verificationLabel"`
	VerificationType  *int64  `json:"verificationType"`
}

type TrendingCategory struct {
	Description *string `json:"description"`
	ID          string  `json:"id"`
	Metrics     struct {
		Posts *int64 `json:"posts"`
		Views *int64 `json:"views"`
	} `json:"metrics"`
	Name string `json:"name"`
}

type TwitterComment struct {
	CommentCore
}

type TwitterEntity struct {
	EntityCore
}

type TwitterList struct {
	CreatedAt   *time.Time `json:"createdAt"`
	Description *string    `json:"description"`
	ID          string     `json:"id"`
	IsPrivate   *bool      `json:"isPrivate"`
	Metrics     struct {
		Followers *int64 `json:"followers"`
		Members   *int64 `json:"members"`
	} `json:"metrics"`
	Name  string      `json:"name"`
	Owner *PostAuthor `json:"owner"`
}

type TwitterPost struct {
	PostCore
	Extended     *TwitterPostExtended `json:"extended,omitempty"`
	Metrics      TwitterPostMetrics   `json:"metrics"`
	QuotedPost   *TwitterPost         `json:"quotedPost,omitempty"`
	RepostedPost *TwitterPost         `json:"repostedPost,omitempty"`
}

type TwitterPostExtended struct {
	ConversationID  *string `json:"conversationId,omitempty"`
	InReplyToPostID *string `json:"inReplyToPostId,omitempty"`
	InReplyToUserID *string `json:"inReplyToUserId,omitempty"`
	Language        *string `json:"language,omitempty"`
	QuotedPostID    *string `json:"quotedPostId,omitempty"`
	RepostedPostID  *string `json:"repostedPostId,omitempty"`
}

type TwitterPostMetrics struct {
	PostMetrics
	Bookmarks *int64 `json:"bookmarks"`
	Quotes    *int64 `json:"quotes"`
}

type TwitterProfile struct {
	ProfileCore
	Extended *TwitterProfileExtended `json:"extended,omitempty"`
}

type TwitterProfileExtended struct {
	Banner            *MediaReference `json:"banner"`
	CreatedAt         *time.Time      `json:"createdAt"`
	Likes             *int64          `json:"likes"`
	Location          *string         `json:"location"`
	Media             *int64          `json:"media"`
	PinnedPostIDs     []string        `json:"pinnedPostIds"`
	WithheldCountries []string        `json:"withheldCountries"`
}

type TwitterSuggestion struct {
	Highlighted *string          `json:"highlighted,omitempty"`
	ID          string           `json:"id"`
	Score       *float64         `json:"score,omitempty"`
	Text        string           `json:"text"`
	Type        *string          `json:"type,omitempty"`
	User        *EntityReference `json:"user,omitempty"`
}
